ARG NODE_ENV=production
ARG NODE_VERSION=20.18.0

FROM ubuntu:noble AS node-builder

ARG NODE_VERSION
WORKDIR /node

RUN apt update && apt install --yes --no-install-recommends \
    curl  \
    ca-certificates  \
    xz-utils \
    && rm -rf /var/lib/apt/lists/* \
    && curl https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz -o node.tar.xz \
    && tar -xf node.tar.xz --strip 1 \
    && rm CHANGELOG.md LICENSE README.md node.tar.xz

FROM ubuntu:noble AS app-base

WORKDIR /app

COPY --from=node-builder /node/ /usr/
COPY /package.json package-lock.json ./
RUN npm clean-install
COPY /tsconfig.json tsconfig.build.json ./
COPY /src src

FROM app-base AS app-builder

ARG NODE_ENV

COPY /nest-cli.json ./
#COPY /env/${NODE_ENV}/mikro-orm.config.ts env/${NODE_ENV}/

RUN npx nest build \
    && npm prune --production \
    && rm \
    dist/tsconfig.build.tsbuildinfo \
    tsconfig.json \
    tsconfig.build.json \
    nest-cli.json \
    package-lock.json

FROM ubuntu:noble AS app

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}
WORKDIR /app

COPY --from=node-builder /node/ /usr/
COPY --from=app-builder /app/ ./
